// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwU5cVeRGJ57UAcJTcBs6jUzWfUE_huTw',
    appId: '1:119193059016:web:bec5f48f7e4eca3062effd',
    messagingSenderId: '119193059016',
    projectId: 'taxi-app-98671',
    authDomain: 'taxi-app-98671.firebaseapp.com',
    storageBucket: 'taxi-app-98671.firebasestorage.app',
    measurementId: 'G-3D0X0TE0YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpauRfucTLdqEy4MkI5VC99_iGEFkN-2g',
    appId: '1:119193059016:android:edb09b6891067ef862effd',
    messagingSenderId: '119193059016',
    projectId: 'taxi-app-98671',
    storageBucket: 'taxi-app-98671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2sxJEUWYcKc-ZWCUQi3dpC_z0JQ22Uhc',
    appId: '1:119193059016:ios:63a92a7b5e5be1dd62effd',
    messagingSenderId: '119193059016',
    projectId: 'taxi-app-98671',
    storageBucket: 'taxi-app-98671.firebasestorage.app',
    iosBundleId: 'de.dispax.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2sxJEUWYcKc-ZWCUQi3dpC_z0JQ22Uhc',
    appId: '1:119193059016:ios:63a92a7b5e5be1dd62effd',
    messagingSenderId: '119193059016',
    projectId: 'taxi-app-98671',
    storageBucket: 'taxi-app-98671.firebasestorage.app',
    iosBundleId: 'de.dispax.app',
  );
}
