version = "3.8.3"
runner.dialect = scala3

maxColumn = 120
assumeStandardLibraryStripMargin = true

indent {
  main = 2
  significant = 2
  callSite = 2
  ctrlSite = 4
}

align {
  preset = most
  multiline = true
  stripMargin = true
}

newlines {
  topLevelStatements = [before]
  beforeMultiline = unfold
  alwaysBeforeElseAfterCurlyIf = true
  avoidInResultType = true
}

rewrite {
  rules = [RedundantBraces, RedundantParens, SortModifiers]
  redundantBraces {
    maxLines = 1
    includeUnitMethods = true
  }
}

docstrings {
  style = Asterisk
  oneline = unfold
}