import XCTest

// Patrol native automation entry point for iOS.
//
// The actual test bodies are generated by the Patrol CLI from the Dart
// integration tests at build time, so this file only needs to expose the
// XCUITest bundle. See the `patrol:` section in pubspec.yaml.
class RunnerUITests: XCTestCase {
    func testFlutterApp() throws {
        // Intentionally empty — Patrol generates the test runner.
    }
}
