database {
  driver = "org.postgresql.Driver"
  url = "jdbc:postgresql://localhost:5432/oktopus"
  url = ${?DATABASE_URL}
  user = "oktopus"
  user = ${?DATABASE_USER}
  password = "oktopus"
  password = ${?DATABASE_PASSWORD}
  
  hikari {
    maximumPoolSize = 10
    minimumIdle = 2
    connectionTimeout = 30000
    idleTimeout = 600000
    maxLifetime = 1800000
  }
}

flyway {
  locations = ["classpath:db/migration"]
  baselineOnMigrate = true
}

server {
  port = 8080
  port = ${?PORT}
}