package com.shevchyk.billing.application

import com.shevchyk.billing.domain.*
import com.shevchyk.core.domain.*
import zio.test.*
import zio.*
import java.time.{Instant, LocalDate}
import java.util.UUID

object PdfGeneratorSpec extends ZIOSpecDefault {

  val companyId       = CompanyId(UUID.randomUUID())
  val clientCompanyId = ClientCompanyId(UUID.randomUUID())

  val testClientCompany = ClientCompany(
    id = clientCompanyId,
    name = "Acme GmbH",
    taxiCompanyId = companyId,
    email = Some("acme@example.com"),
    address = Some("Hauptstraße 1, 80331 München")
  )

  val testClientCompanyMinimal = ClientCompany(
    id = clientCompanyId,
    name = "Minimal Corp",
    taxiCompanyId = companyId,
    email = None,
    address = None
  )

  def makeInvoice(
      items: List[InvoiceItem] = Nil,
      taxRate: BigDecimal = BigDecimal(19),
      notes: Option[String] = None,
      dueDate: Option[LocalDate] = None
  ): Invoice =
    val subtotal = items.foldLeft(BigDecimal(0))(_ + _.total)
    val tax      = subtotal * taxRate / 100
    Invoice(
      id = InvoiceId(UUID.randomUUID()),
      number = "INV-2026-0001",
      clientCompanyId = clientCompanyId,
      taxiCompanyId = companyId,
      status = InvoiceStatus.Draft,
      periodFrom = LocalDate.of(2026, 5, 1),
      periodTo = LocalDate.of(2026, 5, 31),
      subtotalAmount = subtotal,
      taxRate = taxRate,
      taxAmount = tax,
      totalAmount = subtotal + tax,
      currency = "EUR",
      notes = notes,
      dueDate = dueDate,
      items = items
    )

  def makeItem(description: String, quantity: BigDecimal, unitPrice: BigDecimal): InvoiceItem =
    InvoiceItem(
      id = InvoiceItemId(UUID.randomUUID()),
      invoiceId = InvoiceId(UUID.randomUUID()),
      rideId = None,
      description = description,
      quantity = quantity,
      unitPrice = unitPrice,
      total = quantity * unitPrice,
      createdAt = Instant.parse("2026-05-15T10:00:00Z")
    )

  def spec = suite("PdfGenerator")(
    suite("generateBytes")(
      test("generates non-empty PDF bytes for empty invoice") {
        val invoice = makeInvoice()
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("generated bytes start with PDF magic number") {
        val invoice = makeInvoice()
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          val header = new String(bytes.take(4))
          assertTrue(header == "%PDF")
        }
      },
      test("generates PDF with single item") {
        val items   = List(makeItem("Airport transfer MUC", BigDecimal(1), BigDecimal(85.00)))
        val invoice = makeInvoice(items = items)
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.length > 1000)
        }
      },
      test("generates PDF with multiple items") {
        val items = List(
          makeItem("Airport transfer MUC", BigDecimal(3), BigDecimal(85.00)),
          makeItem("City ride", BigDecimal(5), BigDecimal(25.00)),
          makeItem("Long distance", BigDecimal(1), BigDecimal(200.00))
        )
        val invoice = makeInvoice(items = items)
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("generates PDF with zero tax rate") {
        val items   = List(makeItem("Ride", BigDecimal(2), BigDecimal(50.00)))
        val invoice = makeInvoice(items = items, taxRate = BigDecimal(0))
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("generates PDF with notes") {
        val items   = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00)))
        val invoice = makeInvoice(items = items, notes = Some("Bitte innerhalb von 14 Tagen zahlen."))
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("generates PDF with due date") {
        val items   = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00)))
        val invoice = makeInvoice(items = items, dueDate = Some(LocalDate.of(2026, 6, 15)))
        PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("generates PDF for client company without optional fields") {
        val invoice = makeInvoice()
        PdfGenerator.generateBytes(invoice, testClientCompanyMinimal, "TestTaxi GmbH").map { bytes =>
          assertTrue(bytes.nonEmpty)
        }
      },
      test("larger invoice produces larger PDF than empty invoice") {
        val emptyInvoice = makeInvoice()
        val items        = (1 to 20).toList.map(i => makeItem(s"Ride $i", BigDecimal(1), BigDecimal(50 + i)))
        val fullInvoice  = makeInvoice(items = items)
        for {
          emptyBytes <- PdfGenerator.generateBytes(emptyInvoice, testClientCompany, "TestTaxi GmbH")
          fullBytes  <- PdfGenerator.generateBytes(fullInvoice, testClientCompany, "TestTaxi GmbH")
        } yield assertTrue(fullBytes.length > emptyBytes.length)
      }
    ),
    suite("generateToFile")(
      test("writes PDF to temp file and returns path") {
        val invoice = makeInvoice(items = List(makeItem("Test Ride", BigDecimal(1), BigDecimal(99.00))))
        val path    = s"/tmp/test-invoice-${UUID.randomUUID()}.pdf"
        PdfGenerator.generateToFile(invoice, testClientCompany, "TestTaxi GmbH", path).map { returnedPath =>
          assertTrue(returnedPath == path)
        }
      },
      test("written file bytes match generateBytes output") {
        val invoice = makeInvoice(items = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00))))
        val path    = s"/tmp/test-invoice-${UUID.randomUUID()}.pdf"
        for {
          expected <- PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH")
          _        <- PdfGenerator.generateToFile(invoice, testClientCompany, "TestTaxi GmbH", path)
        } yield assertTrue(expected.nonEmpty)
      }
    )
  )
}
