package com.shevchyk.billing.application

import com.shevchyk.billing.domain.*
import com.shevchyk.core.domain.*
import zio.test.*
import zio.*
import java.nio.file.{Files, Path}
import java.time.{Instant, LocalDate}
import java.util.UUID

object PdfGeneratorSpec extends ZIOSpecDefault {

  val companyId       = CompanyId(UUID.randomUUID())
  val clientCompanyId = ClientCompanyId(UUID.randomUUID())

  val testClientCompany = ClientCompany(
    id = clientCompanyId,
    name = "Acme GmbH",
    taxiCompanyId = companyId,
    email = Some("acme@example.com"),
    address = Some("Hauptstraße 1, 80331 München")
  )

  val testClientCompanyMinimal = ClientCompany(
    id = clientCompanyId,
    name = "Minimal Corp",
    taxiCompanyId = companyId,
    email = None,
    address = None
  )

  def makeInvoice(
      items: List[InvoiceItem] = Nil,
      taxRate: BigDecimal = BigDecimal(19),
      notes: Option[String] = None,
      dueDate: Option[LocalDate] = None
  ): Invoice =
    val subtotal = items.foldLeft(BigDecimal(0))(_ + _.total)
    val tax      = subtotal * taxRate / 100
    Invoice(
      id = InvoiceId(UUID.randomUUID()),
      number = "INV-2026-0001",
      clientCompanyId = clientCompanyId,
      taxiCompanyId = companyId,
      status = InvoiceStatus.Draft,
      periodFrom = LocalDate.of(2026, 5, 1),
      periodTo = LocalDate.of(2026, 5, 31),
      subtotalAmount = subtotal,
      taxRate = taxRate,
      taxAmount = tax,
      totalAmount = subtotal + tax,
      currency = "EUR",
      notes = notes,
      dueDate = dueDate,
      items = items
    )

  def makeItem(description: String, quantity: BigDecimal, unitPrice: BigDecimal): InvoiceItem = InvoiceItem(
    id = InvoiceItemId(UUID.randomUUID()),
    invoiceId = InvoiceId(UUID.randomUUID()),
    rideId = None,
    description = description,
    quantity = quantity,
    unitPrice = unitPrice,
    total = quantity * unitPrice,
    createdAt = Instant.parse("2026-05-15T10:00:00Z")
  )

  def spec =
    suite("PdfGenerator")(
      suite("generateBytes")(
        test("generates non-empty PDF bytes for empty invoice") {
          val invoice = makeInvoice()
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("generated bytes start with PDF magic number") {
          val invoice = makeInvoice()
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.take(4).sameElements("%PDF".getBytes("US-ASCII")))
          }
        },
        test("generates PDF with single item") {
          val items   = List(makeItem("Airport transfer MUC", BigDecimal(1), BigDecimal(85.00)))
          val invoice = makeInvoice(items = items)
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.length > 1000)
          }
        },
        test("generates PDF with multiple items") {
          val items   = List(
            makeItem("Airport transfer MUC", BigDecimal(3), BigDecimal(85.00)),
            makeItem("City ride", BigDecimal(5), BigDecimal(25.00)),
            makeItem("Long distance", BigDecimal(1), BigDecimal(200.00))
          )
          val invoice = makeInvoice(items = items)
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("generates PDF with zero tax rate") {
          val items   = List(makeItem("Ride", BigDecimal(2), BigDecimal(50.00)))
          val invoice = makeInvoice(items = items, taxRate = BigDecimal(0))
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("generates PDF with notes") {
          val items   = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00)))
          val invoice = makeInvoice(items = items, notes = Some("Bitte innerhalb von 14 Tagen zahlen."))
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("generates PDF with due date") {
          val items   = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00)))
          val invoice = makeInvoice(items = items, dueDate = Some(LocalDate.of(2026, 6, 15)))
          PdfGenerator.generateBytes(invoice, testClientCompany, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("generates PDF for client company without optional fields") {
          val invoice = makeInvoice()
          PdfGenerator.generateBytes(invoice, testClientCompanyMinimal, "TestTaxi GmbH").map { bytes =>
            assertTrue(bytes.nonEmpty)
          }
        },
        test("larger invoice produces larger PDF than empty invoice") {
          val emptyInvoice = makeInvoice()
          val items        = (1 to 20).toList.map(i => makeItem(s"Ride $i", BigDecimal(1), BigDecimal(50 + i)))
          val fullInvoice  = makeInvoice(items = items)
          for {
            emptyBytes <- PdfGenerator.generateBytes(emptyInvoice, testClientCompany, "TestTaxi GmbH")
            fullBytes  <- PdfGenerator.generateBytes(fullInvoice, testClientCompany, "TestTaxi GmbH")
          } yield assertTrue(fullBytes.length > emptyBytes.length)
        }
      ),
      suite("issuer profile")(
        test("renders issuer bank details and tax IDs into the PDF text") {
          val profile = CompanyBillingProfile(
            companyId = companyId,
            businessType = Some("Mietwagenunternehmen"),
            legalName = Some("Dispax München"),
            addressLine1 = Some("Leopoldstraße 1"),
            addressLine2 = Some("80802 München"),
            phone = Some("+49 89 12345678"),
            email = Some("info@dispax.de"),
            taxNumber = Some("146/116/61550"),
            vatId = Some("DE123456789"),
            bankName = Some("Deutsche Bank"),
            iban = Some("DE24 7007 0024 0393 9543 00"),
            paymentTermsDays = 7,
            invoiceIntro = Some("Ich gestatte mir, ...")
          )
          val invoice = makeInvoice(items = List(makeItem("Ride A", BigDecimal(1), BigDecimal(50.00))))
          PdfGenerator.generateBytes(invoice, testClientCompany, profile).map { bytes =>
            val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
            val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
            val text      = extractor.getTextFromPage(1)
            reader.close()
            assertTrue(
              text.contains("Rechnung"),
              text.contains("Dispax München"),
              text.contains("DE123456789"),
              text.contains("146/116/61550"),
              text.contains("DE24 7007 0024 0393 9543 00"),
              text.contains("Zahlbar innerhalb von 7 Tagen")
            )
          }
        },
        test("renders the recipient (client company) VAT ID into the PDF text") {
          val invoice   = makeInvoice(items = List(makeItem("Ride A", BigDecimal(1), BigDecimal(50.00))))
          val recipient = testClientCompany.copy(vatId = Some("DE999888777"))
          PdfGenerator.generateBytes(invoice, recipient, "TestTaxi GmbH").map { bytes =>
            val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
            val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
            val text      = extractor.getTextFromPage(1)
            reader.close()
            assertTrue(text.contains("DE999888777"))
          }
        }
      ),
      suite("generateReceiptBytes")(
        test("generates a non-empty PDF starting with the magic number") {
          PdfGenerator
            .generateReceiptBytes(
              "Q-ABCD1234",
              "Flughafen München",
              "Marienplatz 1, München",
              Instant.parse("2026-03-05T18:30:00Z"),
              BigDecimal(159.00),
              BigDecimal(19),
              CompanyBillingProfile(companyId, legalName = Some("TestTaxi GmbH")),
              testClientCompany
            )
            .map(bytes => assertTrue(bytes.nonEmpty, bytes.take(4).sameElements("%PDF".getBytes("US-ASCII"))))
        },
        test("renders the receipt content into the PDF text") {
          val profile = CompanyBillingProfile(
            companyId = companyId,
            businessType = Some("Mietwagenunternehmen"),
            legalName = Some("Dispax München"),
            taxNumber = Some("146/116/61550")
          )
          PdfGenerator
            .generateReceiptBytes(
              "Q-ABCD1234",
              "Flughafen München",
              "Marienplatz 1, München",
              Instant.parse("2026-03-05T18:30:00Z"),
              BigDecimal(159.00),
              BigDecimal(19),
              profile,
              testClientCompany
            )
            .map { bytes =>
              val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
              val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
              val text      = extractor.getTextFromPage(1)
              reader.close()
              assertTrue(
                text.contains("Quittung / Rechnung"),
                text.contains("Q-ABCD1234"),
                text.contains("Acme GmbH"),
                text.contains("Flughafen München"),
                text.contains("Marienplatz 1, München"),
                text.contains("Dispax München"),
                // 159,00 gross at 19% → 133,61 net + 25,39 tax (HALF_UP).
                text.contains("159,00 €"),
                text.contains("133,61 €"),
                text.contains("25,39 €")
              )
            }
        },
        test("works for a client company without an address") {
          PdfGenerator
            .generateReceiptBytes(
              "Q-NOADDR01",
              "A",
              "B",
              Instant.parse("2026-03-05T18:30:00Z"),
              BigDecimal(50.00),
              BigDecimal(7),
              CompanyBillingProfile(companyId, legalName = Some("TestTaxi GmbH")),
              testClientCompanyMinimal
            )
            .map(bytes => assertTrue(bytes.nonEmpty))
        },
        test("renders pickup date/time in Europe/Berlin, not UTC (day boundary, winter)") {
          // 2026-01-15T23:30:00Z is 2026-01-16 00:30 in Munich (winter, UTC+1).
          // UTC formatting would wrongly show 15.01.2026 23:30.
          PdfGenerator
            .generateReceiptBytes(
              "Q-TZ-WINTER",
              "Flughafen München",
              "Marienplatz 1, München",
              Instant.parse("2026-01-15T23:30:00Z"),
              BigDecimal(100.00),
              BigDecimal(19),
              CompanyBillingProfile(companyId, legalName = Some("TestTaxi GmbH")),
              testClientCompany
            )
            .map { bytes =>
              val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
              val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
              val text      = extractor.getTextFromPage(1)
              reader.close()
              assertTrue(
                text.contains("16.01.2026 00:30"),
                !text.contains("15.01.2026 23:30")
              )
            }
        },
        test("renders pickup date/time in Europe/Berlin, not UTC (day boundary, summer DST)") {
          // 2026-07-15T22:30:00Z is 2026-07-16 00:30 in Munich (summer, UTC+2).
          // UTC formatting would wrongly show 15.07.2026 22:30.
          PdfGenerator
            .generateReceiptBytes(
              "Q-TZ-SUMMER",
              "Flughafen München",
              "Marienplatz 1, München",
              Instant.parse("2026-07-15T22:30:00Z"),
              BigDecimal(100.00),
              BigDecimal(19),
              CompanyBillingProfile(companyId, legalName = Some("TestTaxi GmbH")),
              testClientCompany
            )
            .map { bytes =>
              val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
              val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
              val text      = extractor.getTextFromPage(1)
              reader.close()
              assertTrue(
                text.contains("16.07.2026 00:30"),
                !text.contains("15.07.2026 22:30")
              )
            }
        },
        test("renders the receipt issuer header date in Europe/Berlin (day boundary)") {
          // The header shows only the date; at 2026-01-15T23:30:00Z Munich is already 16.01.2026.
          PdfGenerator
            .generateReceiptBytes(
              "Q-TZ-HEADER",
              "A",
              "B",
              Instant.parse("2026-01-15T23:30:00Z"),
              BigDecimal(50.00),
              BigDecimal(19),
              CompanyBillingProfile(companyId, legalName = Some("TestTaxi GmbH")),
              testClientCompany
            )
            .map { bytes =>
              val reader    = new com.lowagie.text.pdf.PdfReader(bytes)
              val extractor = new com.lowagie.text.pdf.parser.PdfTextExtractor(reader)
              val text      = extractor.getTextFromPage(1)
              reader.close()
              assertTrue(
                text.contains("16.01.2026"),
                !text.contains("15.01.2026")
              )
            }
        }
      ),
      suite("generateToFile")(
        test("writes PDF to temp file and returns path") {
          val invoice = makeInvoice(items = List(makeItem("Test Ride", BigDecimal(1), BigDecimal(99.00))))
          val path    = s"/tmp/test-invoice-${UUID.randomUUID()}.pdf"
          PdfGenerator.generateToFile(invoice, testClientCompany, "TestTaxi GmbH", path).map { returnedPath =>
            assertTrue(returnedPath == path)
          }
        },
        test("written file bytes match generateBytes output") {
          // generateToFile calls generateBytes once internally and writes those exact bytes.
          // Byte-equality against a second generateBytes call is impossible: OpenPDF embeds a
          // CreationDate timestamp, so two identical invocations differ. We instead verify the
          // file-write path by reading back what generateToFile wrote and confirming it is a
          // non-empty, valid PDF (%PDF magic number present).
          val invoice = makeInvoice(items = List(makeItem("Ride", BigDecimal(1), BigDecimal(50.00))))
          val path    = s"/tmp/test-invoice-${UUID.randomUUID()}.pdf"
          for {
            _            <- PdfGenerator.generateToFile(invoice, testClientCompany, "TestTaxi GmbH", path)
            writtenBytes <- ZIO.attempt(Files.readAllBytes(Path.of(path)))
          } yield assertTrue(
            writtenBytes.nonEmpty,
            writtenBytes.take(4).sameElements("%PDF".getBytes("US-ASCII"))
          )
        },
        test("generateReceiptToFile writes a valid PDF to disk") {
          val path    = s"/tmp/test-receipt-${UUID.randomUUID()}.pdf"
          val profile = com.shevchyk.billing.domain.CompanyBillingProfile(
            companyId = companyId,
            legalName = Some("TestTaxi GmbH")
          )
          for {
            _            <- PdfGenerator.generateReceiptToFile(
                              "Q-RECEIPT01",
                              "Flughafen München",
                              "Marienplatz 1, München",
                              Instant.parse("2026-03-05T18:30:00Z"),
                              BigDecimal(99.00),
                              BigDecimal(19),
                              profile,
                              testClientCompany,
                              path
                            )
            writtenBytes <- ZIO.attempt(Files.readAllBytes(Path.of(path)))
          } yield assertTrue(
            writtenBytes.nonEmpty,
            writtenBytes.take(4).sameElements("%PDF".getBytes("US-ASCII"))
          )
        }
      )
    )
}
